FROM nginx:1.27-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx/ssl && chown -R nginx:nginx /usr/share/nginx/html /etc/nginx/ssl
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
